validation_rules:
  enable_cve_check: true
  enable_abandoned_check: true
  enable_typosquatting_check: true
  enable_version_check: true
  enable_mitre_check: true  # New: Check for MITRE Python weaknesses

abandoned_packages:
  - "oldlib"
  - "unmaintained-pkg"

typosquatting_blacklist:
  - "reqquests"
  - "numpyy"
  - "dj4ngo"

min_versions:
  flask: "2.0.0"
  requests: "2.26.0"
  numpy: "1.21.0"

sources:
  safety_db: "https://pyup.io/api/v1/safety/db/"
  osv_vulnerabilities: "https://api.osv.dev/v1/query"
  mitre_weaknesses: "https://cwe.mitre.org/data/published/cwe-python.json"  # New: MITRE Python CWE list

mitre_weaknesses:
  # List of Python-specific weaknesses from MITRE CWE database
  - CWE-79  # Improper Neutralization of Input During Web Page Generation (XSS)
  - CWE-89  # SQL Injection
  - CWE-94  # Code Injection
  - CWE-20  # Improper Input Validation
  - CWE-502  # Deserialization of Untrusted Data
  - CWE-829  # Inclusion of Functionality from Untrusted Control Sphere
  - CWE-915  # Improperly Controlled Modification of Dynamically-Determined Object Attributes

output:
  report_file: "validation_report.json"
  sbom_file: "sbom.json"

api_endpoints:
  cwe:
    primary: "https://cwe.mitre.org/data/xml/cwec_latest.xml"
    fallback: "https://services.nvd.nist.gov/rest/json/cwe/list/2.0"
  safety_db: "https://raw.githubusercontent.com/pyupio/safety-db/master/data/insecure_full.json"

caching:
  enabled: false
  database: "sqlite"  # or "postgresql"
  path: ".cache/zsbom.db"
  ttl_hours: 24

notifications:
  gchat:
    enabled: false
    webhook_url: "https://chat.googleapis.com/v1/spaces/AAAAdzD-Yps/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=goTzQWpHvNVc8t7XnpCrDBr9LgTWTa7Im0VtIkVUqaA"  # Add your Google Chat webhook URL here
    notification_level: "critical"  # Options: all, critical, none