validation_rules:
  enable_cve_check: true
  enable_abandoned_check: true
  enable_typosquatting_check: true
  enable_version_check: true
  enable_mitre_check: true  # New: Check for MITRE Python weaknesses

# Version consistency configuration for declared vs installed analysis
version_consistency:
  # File priority for dependency resolution (higher priority = preferred source)
  file_priority:
    - "pyproject.toml"
    - "requirements.txt"
    - "setup.py"
    - "setup.cfg"
    - "Pipfile"
  
  # Files to ignore during analysis
  ignore_files:
    - "requirements-dev.txt"
    - "test-requirements.txt"
    - "docs-requirements.txt"
  
  # Cross-file consistency checking settings
  cross_file_analysis:
    enabled: true
    # Treat different but compatible specs as minor conflicts
    compatible_as_minor_conflict: true
    # Log detailed conflict information
    detailed_conflict_logging: true

abandoned_packages:
  - "oldlib"
  - "unmaintained-pkg"

typosquatting_blacklist:
  - "reqquests"
  - "numpyy"
  - "dj4ngo"

min_versions:
  flask: "2.0.0"
  requests: "2.26.0"
  numpy: "1.21.0"

sources:
  cve:
    safety_db:
      enabled: false  # WIP
      url: "https://raw.githubusercontent.com/pyupio/safety-db/master/data/insecure_full.json"
    osv_dev:
      enabled: true
      url: "https://api.osv.dev/v1/querybatch"
  cwe:
    mitre_weaknesses: 
      enabled: true
      url: "https://cwe.mitre.org/data/xml/cwec_latest.xml.zip"  # New: MITRE Python CWE list
    nvd_weaknesses: # Fallback to MITRE CWE
      url: "https://services.nvd.nist.gov/rest/json/cves/2.0"

output:
  report_file: "validation_report.json"
  sbom_file: "sbom.json"
  risk_file: "risk_report.json"
# Risk scoring weights (ZSBOM Risk Scoring Framework v1.0)
risk_model:
  weights:
    # Percentage weights (must total 100%)
    declared_vs_installed: 15  # Version mismatch between declared and installed
    known_cves: 30            # CVEs mapped from OSV.dev/NVD feeds
    cwe_coverage: 20          # Mapped CWEs and their severity classifications
    package_abandonment: 20   # Commit activity, release frequency, and last commit timing
    typosquat_heuristics: 15  # Fuzzy matching and typo-detection against known safe packages
  risk_thresholds:
    low_risk_threshold: 80    # 80-100 = Low Risk
    medium_risk_threshold: 50 # 50-79 = Medium Risk
                              # 0-49 = High Risk


caching:
  enabled: false
  database: "sqlite"  # or "postgresql"
  path: ".cache/zsbom.db"
  ttl_hours: 24

notifications:
  gchat:
    enabled: false
    webhook_url: "https://chat.googleapis.com/v1/spaces/AAAAdzD-Yps/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=goTzQWpHvNVc8t7XnpCrDBr9LgTWTa7Im0VtIkVUqaA"  # Add your Google Chat webhook URL here
    notification_level: "critical"  # Options: all, critical, none
