validation_rules:
  enable_cve_check: true
  enable_abandoned_check: true
  enable_typosquatting_check: true
  enable_version_check: true
  enable_mitre_check: true  # New: Check for MITRE Python weaknesses

abandoned_packages:
  - "oldlib"
  - "unmaintained-pkg"

typosquatting_blacklist:
  - "reqquests"
  - "numpyy"
  - "dj4ngo"

min_versions:
  flask: "2.0.0"
  requests: "2.26.0"
  numpy: "1.21.0"

sources:
  cve:
    safety_db:
      enabled: false  # WIP
      url: "https://raw.githubusercontent.com/pyupio/safety-db/master/data/insecure_full.json"
    osv_dev:
      enabled: true
      url: "https://api.osv.dev/v1/querybatch"
  cwe:
    mitre_weaknesses: 
      enabled: true
      url: "https://cwe.mitre.org/data/xml/cwec_latest.xml.zip"  # New: MITRE Python CWE list
    nvd_weaknesses: # Fallback to MITRE CWE
      url: "https://services.nvd.nist.gov/rest/json/cves/2.0"

output:
  report_file: "validation_report.json"
  sbom_file: "sbom.json"
  risk_file: "risk_report.json"
# Risk scoring weights
risk_model:
  weights:
    version_mismatch: 1
    cve: 3
    cwe: 1
    abandonment: 2
    typosquat: 2
  high_threshold: 6
  medium_threshold: 3


caching:
  enabled: false
  database: "sqlite"  # or "postgresql"
  path: ".cache/zsbom.db"
  ttl_hours: 24

notifications:
  gchat:
    enabled: false
    webhook_url: "https://chat.googleapis.com/v1/spaces/AAAAdzD-Yps/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=goTzQWpHvNVc8t7XnpCrDBr9LgTWTa7Im0VtIkVUqaA"  # Add your Google Chat webhook URL here
    notification_level: "critical"  # Options: all, critical, none
